version: 0.0
os: linux
files:
- source: /
    destination: /home/ubuntu/foo
permissions:
  - object: /home/ubuntu/foo/deploy_hooks
    mode: 755
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
