version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: public/afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: public/applicationstart.sh
      timeout: 100
