version: 0.0
os: linux
files:
  - source: /
    destination: /home/cloudshell-user/ubuntu
hooks:
  AfterInstall:
    - location: ubuntu/afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: ubuntu/applicationstart.sh
      timeout: 100
