version: 0.0
os: linux
files:
  - source: /
    destination: /home/Users/abhis/Desktop/aws_codedeploy_using_github
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
